### ISSUE TITLE
Error on Channel

### ISSUE THREAD

**Issue by LimpYeti** [VirtualZer0/TwitchKeyboard#6]
Hello, no matter what I do i get Error when i go to connect my channel.
![error](https://user-images.githubusercontent.com/121989346/210679237-0759271f-458f-4325-a50e-f59d221457f4.PNG)

**Comment by LimpYeti** [comment]
Also there is nothing in the logs. I have the latest version of the app and of the runtime. It does not matter what i put on channel it will give me that generic error.

**Comment by VirtualZer0** [comment]
Try disabling the firewall and connecting again. If that helps, you'll need to turn the firewall back on and add TwitchKeyboard to the allowed firewall rules.

Here is a description of how you can do this:
https://pureinfotech.com/allow-apps-firewall-windows-10/

If that doesn't help, let me know and I'll put a fix in that will record the exact cause of the error in the log file and then we'll try to figure out what exactly is going wrong in your case.

Translated with www.DeepL.com/Translator (free version)

**Comment by VirtualZer0** [comment]
Try disabling the firewall and connecting again. If that helps, you'll need to turn the firewall back on and add TwitchKeyboard to the allowed firewall rules.

Here is a description of how you can do this:
https://pureinfotech.com/allow-apps-firewall-windows-10/

If that doesn't help, let me know and I'll put a fix in that will record the exact cause of the error in the log file and then we'll try to figure out what exactly is going wrong in your case.

**Comment by LimpYeti** [comment]
I turned off the firewall with no success. I have allowed the app through also with no success.

**Comment by aaskjer** [comment]
ye same issue. doesn't work at all, added firewall exemptions but still gives me error

**Comment by VirtualZer0** [comment]
[TwitchKeyboard.x64.errlog-enabled.zip](https://github.com/VirtualZer0/TwitchKeyboard/files/10362442/TwitchKeyboard.x64.errlog-enabled.zip)

Try this version. If there is an error connecting to the chat, you will see a file connectionError.txt with a detailed description of the problem. Send its contents here so that I have a chance to find the problem.

**Comment by aaskjer** [comment]
crashlog says this:

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'TwitchKeyboard.Windows.MainWindow' that matches the specified binding constraints threw an exception.
 ---> System.Net.HttpListenerException (183): Failed to listen on prefix 'http://localhost:51473/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at TwitchKeyboard.Classes.Services.NotificationService.Start()
   at TwitchKeyboard.Windows.MainWindow..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by LimpYeti** [comment]
Tried your new version with no changes. I dont even get a connectionerror.txt

**Comment by VirtualZer0** [comment]
Yeah, it looks like I didn't cover every possible case. This version should help to find the error. @aaskjer, this error is not related to connection error, try this version as well.

[TwitchKeyboard.x64.errlog-enabled.zip](https://github.com/VirtualZer0/TwitchKeyboard/files/10362821/TwitchKeyboard.x64.errlog-enabled.zip)

**Comment by aaskjer** [comment]
‌‌![image](https://user-images.githubusercontent.com/56720094/211094684-96c9ce7a-1c8b-47c8-9a71-b2363a6745fd.png)
This shows up if i try to run it and it is installed @VirtualZer0 
​‌‌‌‌​‌​​‌‌‌‌​‌‌‌‌​‌​​‌​‌​​​​​‌‌​‌‌​‌​‌‌‌​​​‌​​‌‌‌​​​​‌​​​​​‌

**Comment by VirtualZer0** [comment]
But this is literally the same program that I uploaded earlier, the changes in it had nothing to do with the platform version.

**Comment by VirtualZer0** [comment]
Make sure that you have exactly .NET 6 and exactly the Desktop Runtime version.

**Comment by aaskjer** [comment]
i didn't changed anything. that's the net version i have
![image](https://user-images.githubusercontent.com/56720094/211098285-7ac57338-b10e-4437-8233-af12a00bbfd2.png)

[edit]  @VirtualZer0 
i added "TwitchKeyboard.runtimeconfig.json" from your release files and it startet but still shows an error

Errorlog:
Join error: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Classes.APIModels.TwitchGQL.RewardsRoot[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'error', line 1, position 9.
Join error: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Classes.APIModels.TwitchGQL.RewardsRoot[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'error', line 1, position 9.

**Comment by LimpYeti** [comment]
yeah didnt run for me untill i added the twitchkeyboard.runtimeconfi.json as well
this time i did get a connectionerror.txt and this is what it had.

Join error: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Classes.APIModels.TwitchGQL.RewardsRoot[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'error', line 1, position 9.

**Comment by VirtualZer0** [comment]
Okay, I understand the problem. Most likely Twitch changed the API. Tomorrow I will release a new version that fixes this and a couple of other bugs.

**Comment by VirtualZer0** [comment]
I tried to connect to your channel, but could not find an error, everything connects steadily and the list of channel rewards is successfully loaded. Maybe it's your location or something else that is causing the Twitch API to return a different format response. 
Try this build, it will add a Twitch response dump to the text file.

[TwitchKeyboard.x64.errlog-enabled.zip](https://github.com/VirtualZer0/TwitchKeyboard/files/10366668/TwitchKeyboard.x64.errlog-enabled.zip)

**Comment by aaskjer** [comment]
> I tried to connect to your channel, but could not find an error, everything connects steadily and the list of channel rewards is successfully loaded. Maybe it's your location or something else that is causing the Twitch API to return a different format response. Try this build, it will add a Twitch response dump to the text file.
> 
> [TwitchKeyboard.x64.errlog-enabled.zip](https://github.com/VirtualZer0/TwitchKeyboard/files/10366668/TwitchKeyboard.x64.errlog-enabled.zip)

Found out the last non-standalone release of yours worked fine. i don't know why but it connects without any issues. Some error shows up sometimes at disconnecting it from my channel but after a restart it worked like before. It's only the standalone causing errors like your last linked version still does ![image](https://user-images.githubusercontent.com/56720094/211175889-174b25c7-c35f-4a42-b488-e88395bb6fcb.png)

Errorlog:

Join error: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Classes.APIModels.TwitchGQL.RewardsRoot[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'error', line 1, position 9.
Response:
{"error":"Bad Request","status":400,"message":"invalid request body format"}

**Comment by LimpYeti** [comment]
This is the error i get. For context i am in NA



Join error: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Classes.APIModels.TwitchGQL.RewardsRoot[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'error', line 1, position 9.
Response:
{"error":"Bad Request","status":400,"message":"invalid request body format"}

**Comment by VirtualZer0** [comment]
@LimpYeti this is not good news, considering that some people's connection to Twitch is still working fine. Finding the problem may take a while, but I'll try to help you. Around today or tomorrow (not sure about your time zone) I'll recheck the Twitch API again and release a new full version of the app and see if that fixes your problem.

**Comment by VirtualZer0** [comment]
Twitch's API may have really changed, but they're making these changes gradually by layers of users, so for now the app works for some people.

**Comment by LimpYeti** [comment]
let me know if there is anything i can do to help. If you got a paypal or something ill float some cash your way for your hard work.
if it helps at all i used a VPN and tried while connected to germany, UK, and Spain with no luck.

**Comment by VirtualZer0** [comment]
@LimpYeti can you DM me on Discord? My nickname is VirtualZer0#1799. I think I'll be able to answer you promptly there. You need to make a test request to the Twitch API from your browser to see the response. My time zone is GMT+3, you can try writing any time I'm online.

**Comment by 94HanA** [comment]
![image](https://user-images.githubusercontent.com/111541485/217863142-403063c5-b778-4012-bd87-0d59f6a8ff26.png)
![image](https://user-images.githubusercontent.com/111541485/217863200-82f721df-8a9c-41cb-af61-eeffd32cad02.png)

I have exactly same problem. I send a friend request to you on discord, could you help me?

**Comment by VirtualZer0** [comment]
For anyone with a similar problem, there is a temporary version available at this link. I want to add more functionality in the next full update, so it's a bit delayed.

https://vz0.dev/storage/Expx64v2.zip

**Comment by mert-ersoy** [comment]
I am experiencing the same error. The download link provided seems to be broken. Is there a possibility that it can be fixed?

**Comment by VirtualZer0** [comment]
> I am experiencing the same error. The download link provided seems to be broken. Is there a possibility that it can be fixed?

Yes, I fixed the link, try downloading again

**Comment by VirtualZer0** [comment]
The full update will be this fall, I've had some personal stuff going on but will be back to work soon enough
